FROM node:alpine3.20 AS build

ARG BUILD_CONFIG=docker

WORKDIR /app

COPY package.json ./
RUN npm install

COPY ./ /app
RUN npm run build:$BUILD_CONFIG

FROM nginx:1.24

COPY --from=build /app/dist/front-end /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80