services:
  front:
    image: ps6-dndevelopers/front
    build:  ../front-end
    ports:
      - "8080:80"
    depends_on:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
  
  back:
    image: ps6-dndevelopers/back
    build:  ../backend
    ports:
      - "8081:9428"
    volumes:
      - ../backend/database:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9428/api/status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
  
  playwright:
    build:
      dockerfile: "Dockerfile.test"
      context: ../front-end
    environment:
      - TEST_URL=http://front
    volumes:
      - test-results:/front-end/test-results
    depends_on:
      front:
        condition: service_healthy

volumes:
  test-results:
  back:
