services:
  front:
    image: ps6-dndevelopers/front
    build:
      context: ../front-end
      args:
        - BUILD_CONFIG=docker
    ports:
      - "8080:80"
    depends_on:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  back:
    image: ps6-dndevelopers/back
    build:  ../backend
    ports:
      - "8081:9428"
    volumes:
      - ../backend/database:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9428/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3